# docker run --env MODE=standalone --name alone-nacos -d -p 28848:8848 nacos/nacos-server
version: "3.1"
services:
  alone-nacos: # 服务名称
    image: nacos/nacos-server # 镜像名
    container_name: alone-nacos # 容器名称
    restart: always # 开机启动项只要docker 启动就会启动
    environment:
      - MODE=standalone # 初始密码
    # env_file:  # 等同于environment
    #   - ./nacos/nacos-config.env
    ports:
      # - "8848:8848"
      # - "9555:9555"
      - 28848:8848 # 设置对外暴露端口，指定端口映射
    volumes: # 映射数据目录到宿主机，方便修改配置
      - ../conf/nacos_conf/:/home/nacos/conf/
    networks:
      - mogu

networks:
  mogu:
    external: true
# docker run -v /usr/local/tmp/fast-docker-compose/conf/nacos_conf/application.properties:/home/nacos/conf/application.properties --env MODE=standalone --name alone-nacos -d -p 28848:8848 nacos/nacos-server
