version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
#      args:
#        buildno: 1
    ports:
      - 8070:8070
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    container_name: mysql_container
    ports:
      - 3306:3306
    env_file:
      - ./common.env
#    environment:
#      - "MYSQL_ROOT_PASSWORD=123456"
#      - "MYSQL_DATABASE=aaa"
    volumes:
      - /root/sorf/mysql/data:/var/lib/mysql
      - /root/sorf/mysql/conf.d:/etc/mysql/conf.d
#volumes:
#  mysqldata:
