version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    #      args:
    #        buildno: 1
    ports:
      - 8070:8070
    depends_on:
      - mysql
      - redis
      - web
  mysql:
    image: mysql:8
    container_name: mysql_container
    ports:
      - 3306:3306
    env_file:
      - ./common.env
    #    environment:
    #      - "MYSQL_ROOT_PASSWORD=123456"
    #      - "MYSQL_DATABASE=aaa"
    volumes:
      - /root/sorf/mysql/data:/var/lib/mysql
      - /root/sorf/mysql/conf.d:/etc/mysql/conf.d
  #    command: docker exec -i mysql_container sh -c 'exec mysql -uroot -p"123456"' < ./all-databases.sql
  redis:
    image: redis:7.0.4
    ports:
      - 6379:6379
    volumes:
      - /root/sorf/redis/conf:/usr/local/etc/redis
      - /root/sorf/redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
  web:
    image: nginx:1.23.1
    ports:
      - "80:80"
    volumes:
      - /root/sorf/nginx/html:/usr/share/nginx/html
      - /root/sorf/nginx/cache:/var/cache/nginx
      - /root/sorf/nginx/log:/var/log/nginx
      - /root/sorf/nginx/conf:/etc/nginx/conf.d
      - /root/sorf/nginx.conf:/etc/nginx/nginx.conf
    command: [ nginx-debug, '-g', 'daemon off;' ]

#volumes:
#  mysqldata:
