version: "3.1"
services:
  nacos-nginx: # 服务名称
    image: nginx # 镜像名
    container_name: nacos-nginx # 容器名称
    restart: always # 开机启动项只要docker 启动就会启动
    # environment: # 会覆盖env_file的配置
    #   - MYSQL_ROOT_PASSWORD=123456 # 初始密码
    # env_file:
    #   - ./common.env
    #   - ./apps/web.env
    #   - /opt/secrets.env
    ports:
      - 80:80 # 设置对外暴露端口，指定端口映射
    : # 映射数据目录到宿主机，方便修改配置
      - ../logs/nginx_logs:/var/log/nginx
      - ../data/mysql_data/html:/usr/share/nginx/html
      - ../conf/mysql_conf/nginx.conf:/etc/nginx/nginx.conf
      - ../conf/mysql_conf/default.conf:/etc/nginx/conf.d/default.conf
#     networks:
#       - mogu
# networks:
#   mogu:
#     external: true # 定义为外部资源

# docker run -d -p 80:80 --name nginx-test -v /usr/local/tmp/fast-docker-compose/logs/nginx_logs:/var/log/nginx -v /usr/local/tmp/fast-docker-compose/data/nginx_data/html:/usr/share/nginx/html -v /usr/local/tmp/fast-docker-compose/conf/nginx_conf/nginx.conf:/etc/nginx/nginx.conf -v /usr/local/tmp/fast-docker-compose/conf/nginx_conf/default.conf:/etc/nginx/conf.d/default.conf nginx

