version: "3"
volumes:
  mysqlData:
services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
    volumes:
      - mysqlData:/var/lib/mysql
      - /root/sorf/mysql/conf.d:/etc/mysql/conf.d
  #    command: docker exec -i mysql_container sh -c 'exec mysql -uroot -p"123456"' < ./all-databases.sql
